#!/bin/bash -ex

REPO=http://repos.rcn-ee.com/debian
VERSION=2017.07.18~buster+20170718
KEYRING=rcn-ee-archive-keyring
export VERSION KEYRING REPO

# Retrieve the package with Robert's signing key from his repository
wget $REPO/pool/main/r/$KEYRING/${KEYRING}_${VERSION}_all.deb

# Create a debian package with an apt sources line pointing to the above repo
echo deb $REPO buster main > rcn-ee.com
mhamakedeb apt.rcn-ee.csv $VERSION armhf

# move the debs to the target directory
mkdir -p debs/bionic
mv *.deb debs/bionic
